SEED: 7
DEBUG: False
LOG_FREQ: 1000
SAVE_CHECKPOINTS: [10]
INFERENCE_CHECKPOINT: 10

TRAINER:
  LR: 1e-4
  BATCH_SIZE: 8
  EPOCHS: 10
  OPTIMIZER: 'adamw'

MODEL:
  TYPE: 'ds_unet_mmtm'
  OUT_CHANNELS: 1
  LOSS_TYPE: 'PowerJaccardLoss'
  TOPOLOGY: [64, 128,]

DATALOADER:
  NUM_WORKER: 2
  SHUFFLE: True
  LABEL: 'buildings'
  LABEL_THRESH: 0.0
  MODE: 'fusion'
  SENTINEL1_BANDS: ['VV', 'VH']
  SENTINEL2_BANDS: ['B2', 'B3', 'B4', 'B8']

AUGMENTATION:
  CROP_SIZE: 256
  RANDOM_FLIP: True
  RANDOM_ROTATE: True
  COLOR_SHIFT: False
  GAMMA_CORRECTION: False

DATASET:
  TRAINING: [
    'albuquerque', 'atlantaeast', 'atlantawest', 'charlston', 'columbus', 'dallas', 'denver', 'elpaso', 'houston',
    'kansascity', 'lasvegas', 'losangeles', 'miami', 'minneapolis', 'montreal', 'phoenix', 'quebec', 'saltlakecity',
    'sandiego', 'santafe', 'seattle', 'stgeorge', 'toronto', 'tucson', 'winnipeg', 'sydney'
  ]
  VALIDATION: ['calgary', 'newyork', 'sanfrancisco', 'vancouver']



